# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dptm <- function(pts, myMeans, wgts, ppDim, kkMean, nn) {
    .Call('_kamila_dptm', PACKAGE = 'kamila', pts, myMeans, wgts, ppDim, kkMean, nn)
}

rowMax <- function(inMat) {
    .Call('_kamila_rowMax', PACKAGE = 'kamila', inMat)
}

rowMin <- function(inMat) {
    .Call('_kamila_rowMin', PACKAGE = 'kamila', inMat)
}

rowMaxInds <- function(inMat) {
    .Call('_kamila_rowMaxInds', PACKAGE = 'kamila', inMat)
}

sumMatList <- function(x) {
    .Call('_kamila_sumMatList', PACKAGE = 'kamila', x)
}

getIndividualLogProbs <- function(catFactorNum, catWeights, logProbsCond_i) {
    .Call('_kamila_getIndividualLogProbs', PACKAGE = 'kamila', catFactorNum, catWeights, logProbsCond_i)
}

calcCatLogLiks <- function(catFactorNum, catWeights, logProbsCond_i) {
    .Call('_kamila_calcCatLogLiks', PACKAGE = 'kamila', catFactorNum, catWeights, logProbsCond_i)
}

aggregateMeans <- function(conVar, membNew, kk) {
    .Call('_kamila_aggregateMeans', PACKAGE = 'kamila', conVar, membNew, kk)
}

jointTabSmoothedList <- function(catFactorNum, membNew, numLev, catBw, kk) {
    .Call('_kamila_jointTabSmoothedList', PACKAGE = 'kamila', catFactorNum, membNew, numLev, catBw, kk)
}

updateLogProbs <- function(catFactorNum, membNew, numLev, catBw, kk) {
    .Call('_kamila_updateLogProbs', PACKAGE = 'kamila', catFactorNum, membNew, numLev, catBw, kk)
}

interpRadialKde <- function(y, maxEval, pdim, evalPoints, takeLog = FALSE) {
    .Call('_kamila_interpRadialKde', PACKAGE = 'kamila', y, maxEval, pdim, evalPoints, takeLog)
}

calcPsCpp <- function(testMemb, teIntoTr, numClust) {
    .Call('_kamila_calcPsCpp', PACKAGE = 'kamila', testMemb, teIntoTr, numClust)
}

