# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dptm <- function(pts, myMeans, wgts, ppDim, kkMean, nn) {
    .Call('_kamila_dptm', PACKAGE = 'kamila', pts, myMeans, wgts, ppDim, kkMean, nn)
}

rowMax <- function(inMat) {
    .Call('_kamila_rowMax', PACKAGE = 'kamila', inMat)
}

rowMin <- function(inMat) {
    .Call('_kamila_rowMin', PACKAGE = 'kamila', inMat)
}

rowMaxInds <- function(inMat) {
    .Call('_kamila_rowMaxInds', PACKAGE = 'kamila', inMat)
}

sumMatList <- function(x) {
    .Call('_kamila_sumMatList', PACKAGE = 'kamila', x)
}

getIndividualLogProbs <- function(catFactorNum, catWeights, logProbsCond_i) {
    .Call('_kamila_getIndividualLogProbs', PACKAGE = 'kamila', catFactorNum, catWeights, logProbsCond_i)
}

aggregateMeans <- function(conVar, membNew, kk) {
    .Call('_kamila_aggregateMeans', PACKAGE = 'kamila', conVar, membNew, kk)
}

jointTabSmoothedList <- function(catFactorNum, membNew, numLev, catBw, kk) {
    .Call('_kamila_jointTabSmoothedList', PACKAGE = 'kamila', catFactorNum, membNew, numLev, catBw, kk)
}

